docs: update the connectionless documentation
hyperledger-identus/docs pull request #196
Opened 2024-10-29 01:16 UTC by chereseeriepa

2024-11-14 13:43 UTC, elribonazo requested changes

2024-11-14 13:43 UTC, elribonazo commented on documentation/docs/quick-start.md
> +    (message) => message.piuri === 'https://didcomm.org/issue-credential/3.0/issue-credential'
Propose to replace it from
'https://didcomm.org/issue-credential/3.0/issue-credential'
to 
SDK.ProtocolType.DidcommIssueCredential

2024-11-14 13:43 UTC, elribonazo commented on documentation/docs/quick-start.md
> +    (message) => message.piuri === 'https://didcomm.org/issue-credential/3.0/offer-credential'
Proposing to change 'https://didcomm.org/issue-credential/3.0/offer-credential' to SDK.ProtocolType.DidcommOfferCredential

2025-01-13 17:20 UTC, FabioPinheiro commented
@elribonazo why is this not merged?

2025-01-13 17:20 UTC, FabioPinheiro approved these changes
LGTM

2025-02-28 10:14 UTC, yshyn-iohk commented
@chereseeriepa, could you rebase your commits on top of the main branch to resolve conflicts?

2025-08-02 21:13 UTC, closed without merging